# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      KEY: ${{ secrets.KEY }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          while read -r cmd
          do
            eval sudo $cmd
          done < <(Rscript -e 'writeLines(remotes::system_requirements("ubuntu", "20.04"))')
          sudo apt-get install libnode-dev
          sudo apt-get install libsodium-dev

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            any::covr
            any::sodium
          needs: coverage

      - name: Decrypt config and set ready for travis checks
        run: |
          writeBin(sodium::data_decrypt(readRDS("rdhs.json.tar.enc"), sodium::hash(charToRaw(Sys.getenv("KEY")))),"rdhs.json.tar")
          unzip("rdhs.json.tar")
        shell: Rscript {0}

      - name: Test coverage
        run: |
          Sys.setenv("rdhs_RENVIRON_PERMISSION"=1)
          Sys.setenv("NOT_CRAN"="true")
          Sys.setenv("TRAVIS"="true")
          covr::codecov(quiet = FALSE)
        shell: Rscript {0}
